spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot1
    username: AppAdmin
    password: praveen
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
