message: praveen test
name: raju test
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboottst
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
