meassge: HiTST
spring: 
  datasource: 
    driverClassName: com.mysql.jdbc.Driver
    password: ~
    url: "jdbc:mysql://localhost:3306/springboottst"
    username: root
  jpa: 
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true

