message: values from dev
name: raju dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdev
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
